### ISSUE TITLE
ut_j9mm.h includes jni.h when compiled without -DUT_DIRECT_REGISTRATION

### ISSUE THREAD

**Issue by rwy0717** [eclipse/omr#115]
`ut_j9mm.h` includes `jni.h` when compiled without `-DUT_DIRECT_REGISTRATION`. OMR should not include a J9 header file, even under unusual defines.

```
In file included from ../omr/gc/include/ModronAssertions.h:24:0,
                 from ../omrglue/ArrayletObjectModel.hpp:23,
                 from ../omr/gc/base/ArrayObjectModel.hpp:29,
                 from ../omr/gc/base/GCExtensionsBase.hpp:30,
                 from ../src/isolate.cc:61:
../omr/gc/base/ut_j9mm.h:9:17: fatal error: jni.h: No such file or directory
```

Relevant lines:

```
#include "ute_module.h"
#if !defined(UT_DIRECT_TRACE_REGISTRATION)
#include "jni.h"
#endif /* !defined(UT_DIRECT_TRACE_REGISTRATION) */
```

**Comment by alin00** [comment]
ut_*.h are generated by tracegen. When tracegen was written, our hands were tied by the requirement to match the output of the Java version of the tool.

Since then, we've intermittently discussed deleting the UT_DIRECT_TRACE_REGISTRATION flag, and the code where UT_DIRECT_TRACE_REGISTRATION is !defined.

I suspect that OMR and J9 VM no longer require the code where !defined(UT_DIRECT_TRACE_REGISTRATION). However, some other component of the IBM Java SDK likely still requires that code. If we remove this output from tracegen, then that component either needs to be updated, or they will not be able to use this version of tracegen (and we will need to continue maintaining the Java version of tracegen for them).
