### ISSUE TITLE
Updating vendored components

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#1358]
We have a couple of third party components that we've chosen to vendor (redistribute in our source repo): Notably  Google Test and PugiXML. 

What kind of process would have to be followed to update these components (I am thinking mostly from a legal perspective, and mostly GTest)

**Comment by smlambert** [comment]
Though this doesn't answer the "from a legal perspective", I think it is fair to say that we do not have an official process.  Originally, there was an AWSOM request in order to distribute those open-source projects.  Gtest required a small change to run on z/OS machines that was not contributed back to gtest (due to the nature of it), we intentionally kept that change segregated, to make it easy to upgrade.

**Comment by mstoodle** [comment]
@smlambert AWSOM is an IBM thing: it is not relevant in this project.

@mgaudet Eclipse defines the process: we will have to file a CQ on the version you want to update it to before it can be done. Typically version update requests should be turned around pretty quickly unless something has happened in the interim (like the license was changed).

What specific GTest version are you thinking to update to? Once you file the pull request to update it, any of the committers can open the CQ.

**Comment by 0xdaryl** [comment]
We will submit a PR to upgrade GTest to version 1.8 once we've tested it works with our current tests.  This is needed in order to build and run tests using the new Tril framework.  The licenses between 1.7 and 1.8 are byte-for-byte identical.

**Comment by mstoodle** [comment]
I think this one has been addressed; please reopen if not.
