### ISSUE TITLE
OSX cannot map memory below 4GB

### ISSUE THREAD

**Issue by alin00** [eclipse/omr#15]
The OSX version of the port library cannot map memory below 4GB.

OSX cannot map memory below 4GB, so omrmem_allocate_memory32() will always return NULL.
If we can't allocate memory below 4G, this may prevent us from supporting features like compressedrefs GC.

There may be an option that allows forcing mmap() below 4GB to succeed. It requires linking the executable (does not work for libraries) with option "-pagezero_size x".

**Comment by ezephir** [comment]
I'd like to help with this issue. I believe the solution in the issue description to be correct. Is there a specific action item or goal for this issue?

**Comment by ezephir** [comment]
@fjeremic Thank you for the excellent and helpful explanation!

So, the issue here is that Clang includes a segment in executable files, `__PAGEZERO`, that's loaded at the beginning of the address space and cannot be read from or written to. This file is used to catch bad memory references. On 32-bit executables in macOS, this segment takes up the first 8 bytes by default -- enough to trap access to 0x0. On 64-bit executables, the segment takes up the first 4GB by default, preventing any 32 bit memory addresses from being valid.

The `pagezero_size` flag mentioned in this file can be used to change the executable's `__PAGEZERO` segment size. I believe the minimum size is 8 bytes. A path forward is for interested OMR consumers to shorten the segment via this flag. This should cause mmap to work as expected.

**Comment by 0xdaryl** [comment]
@babsingh, can this be closed now?

**Comment by babsingh** [comment]
@0xdaryl yes, this can be closed. https://github.com/eclipse/omr/pull/3045 is the fix for this issue.
