### ISSUE TITLE
Create documentation for the Eclipse OMR project - Contributions welcome! 

### ISSUE THREAD

**Issue by dorrab** [eclipse/omr#165]
Eclipse OMR is in need of better documentation and we welcome your help.

Please use this Issue to: 
- discuss documentation related topics  
- identify any missing documentation. 

You are more than welcome to contribute directly by sending pull requests ([PR](https://github.com/eclipse/omr/pulls)) or let us know about any sections that you feel are poorly documented and need to improve.

Thank you

**Comment by charliegracie** [comment]
@dorrab is there a starting point for the website? It will be easier to contribute text/documentation once there is a starting point up and running.

**Comment by dorrab** [comment]
Yes, a website using Jekyll is ready. 
We have a few outstanding questions to resolve before contributing the code. One of them from 
@mstoodle. He asked if the website should be contributed to the master branch under a "docs" directory ? Or would it be better to have it in a separate branch like "gh-pages" ? 
Any thoughts?

**Comment by ktbriggs** [comment]
Do we have a common store or repo where prospective web structure and content can be checked in to be reviewed and tracked? For example - I have a blog post on DropBox, where I posted it for review and where it is accessible only to IBMers AFAIK. If it were on github reviewers could contribute feedback and track changes inline with current workflows. I think github submodule is a natural choice for storing and tracking documentation. Instead of a separate branch, it might be worth considering packaging the web site and other documentation artifacts as a git submodule.

Some thought should be given to separating blogs and articles (which can stand alone and be published independently of the website) and the structural elements of the web site. Also, we should have some guidance as to appropriate format and content of API-level documentation -- like templates for documenting components and public classes and  methods.

**Comment by Krovatkin** [comment]
@mstoodle , @vijaysun-omr , I'm putting together a small write-up on Inliner. It's not much at this point, but I was wondering if I could open a PR and keep building on it or would you prefer to see only the final product?

**Comment by mstoodle** [comment]
Hi @krovatkin,good to hear from you! So long as the write-up matches the current state of the inliner, which I believe has changed somewhat since your last direct exposure :) , we would certainly welcome it! I would suggest writing up a skeleton, sharing that for review, and then filling in the pieces at whatever pace you can manage. How does that sound?

Thanks for reaching out, Nick!

**Comment by mstoodle** [comment]
@ktbriggs Sorry nobody responded to your question. The current web site is in a separate repository at https://github.com/eclipse/omr.website . The plan is for design documentation to live in this repository alongside the code, and we'll set up some way to view that documentation if that's all you want to see. We'll get some links in the web site to point at the documentation here.

The web site is still a bit rough with lots of "content to be added later" sections, but it's now online at https://www.eclipse.org/omr .

**Comment by 0xdaryl** [comment]
The precedent over the past few years has been to produce documentation in Markdown format that lives in an appropriate place in the `doc/` folder.  Contributions are always welcome there.
