### ISSUE TITLE
OMR make recipe does not support incremental compilation for tests

### ISSUE THREAD

**Issue by ktbriggs** [eclipse/omr#1831]
A full build is required in order for omrgctest to pick up incremental source changes (at least for omr/gc/base/standard source). To see this:

1. clone omr
2. cd omr
3. export INCLUDE_OMRTEST=true
4. make clean &> make.clean.out
5. make -f run_configure.mk clean all &> make.configure.out
6. make &> make.all.out
7. ./omrgctest -logLevel=warn
8. modify Scavenger.cpp to add a println() in MM_Scavenger::initialize()
9. export INCLUDE_OMRTEST=true
10. make &>make.incremental.out
11. ./omrgctest -logLevel=warn #< no println output from MM_Scavenger::initialize()
12. export INCLUDE_OMRTEST=true
13. make clean &> make.clean.out
14. make -f run_configure.mk clean all &> make.configure.out
15. make &> make.all.out
16. ./omrgctest -logLevel=warn #< see println output from MM_Scavenger::initialize()

From the make.incremental.out file contents, it looks like Scavenger.cpp gets compiled, Scavenger.o get ar'ed into a couple of libraries, but doesn't get linked into omrgctest.

**Comment by rwy0717** [comment]
We never create a dependency between a module and it's `MODULE_STATIC_LIBS` (or shared libs for that matter).  I think this is because it is difficult to resolve a library name to a real file. Maybe this would be easier if we distinguished between system libraries and internal libraries, but it would still be a lot of work after that. I don't expect there to be much interest in such a big change to the autotools build system.

The good news is, the cmake build system should Just Work™.

**Comment by charliegracie** [comment]
This issue will be handled by moving to CMake.  I do not think we will be investing in the auto tools story moving forward

**Comment by youngar** [comment]
Closing, and we'll be using the new issue #2449 to follow the progress.
