### ISSUE TITLE
Provide some label documentation

### ISSUE THREAD

**Issue by dchopra001** [eclipse/omr#1953]
It would be nice to have some label documentation. It will make it easier to filter issues when you know exactly what to look for. For example, knowing the differences/similarities between `help wanted` and `beginner` would be useful as I think these fall within the same general category.

**Comment by 0xdaryl** [comment]
You're right that the label taxonomy could use more documentation.  To address your specific questions:

`beginner` generally refers to a task that would be suitable for someone new to the project with little experience with either the technology or even open-source projects and processes.  They are intended for anyone who wants to gently get their feet wet on building, testing, or familiarizing themselves with part of the code base.

`help wanted` refers to a task that has value to the project but no immediate human resources to undertake it.  Those that are looking to complete a task that someone isn't already working on can tackle these.

**Comment by mgaudet** [comment]
So, I'm prepping PR to check in the above description into CONTRIBUTING.md, but now I'm faced with my own classification question: What do you see as the distinction between `backlog` and `help wanted`?

**Comment by 0xdaryl** [comment]
`backlog` to me means a tangible task that will eventually get done (or is generally agreed will get done).  If an issue doesn't have a backlog tag then that could mean it's too nebulous, or is a question, or a discussion issue for example.

`help wanted` is a request for resource on an issue in order to make progress.  No one has declared they wish to claim a particular task.

**Comment by 0xdaryl** [comment]
This has been merged in the CG.  Closing.
