### ISSUE TITLE
Spark daemon stops running with Java V8 SR5

### ISSUE THREAD

**Issue by manqingl** [eclipse/omr#2076]
When Java is launched with nohup in ZOS, nohup will register a SIGHUP signal handler to ignore the SIGHUP signal.

In Java 8 SR 5, the above SIGHUP signal handler is overwritten and therefore the Java process will be terminated with a SIGHUP signal.

**Comment by hangshao0** [comment]
The issue here is that when user is calling omrsig_sigaction_internal() with second parameter NULL to query the sigaction for the registered signal, we failed to return the existing sigaction. The caller checks the returned sigaction (which is empty), which leads the caller to register a new sigaction/handler, overwriting the existing one.

**Comment by mstoodle** [comment]
This bug should not be expressed a bug in "Java 8 SR5" vs. "Java 8 SR4" since those are not Eclipse OMR releases...
