### ISSUE TITLE
Enable travis.ci continuous builds for OMR

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/omr#21]
Pull request #20 added a .travis.yml file for the Travis.CI build engine.  To enable continuous builds, the the github repo needs to enable travis integration.  See https://docs.travis-ci.com/user/getting-started/

Note: You can only enable Travis CI builds for repositories you have admin access to.

Can an admins enable the travis integration?

**Comment by DanHeidinga** [comment]
@eclipsewebmaster Is this something the project admins can do or does it need Eclipse help?

**Comment by mstoodle** [comment]
I have also sent a direct request to the eclipse webmaster to enable the repository for us. I tried but apparently do not have sufficient admin rights.

**Comment by mstoodle** [comment]
Which got me to open this bug for the request: https://bugs.eclipse.org/bugs/show_bug.cgi?id=489970

**Comment by DanHeidinga** [comment]
Thanks Mark.

**Comment by mgaudet** [comment]
Looks like this can be resolved! (The [eclipse item](https://bugs.eclipse.org/bugs/show_bug.cgi?id=489970) is resolved, and we got a Travis build for PR#25.

**Comment by alin00** [comment]
There's a build setup or test problem. #25 / #26 changed no code, so the problem isn't caused by that patch.

We shouldn't use this build to gate pull request acceptance if it's not totally reliable.

I'm not sure how to address this in #26 now - there's no code "fix" I can apply. How am I supposed to change the state of this check?

The test failure is NUMA-related:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/117539288/log.txt

[0;32m[ RUN      ] [mThreadCreateTest.NumaSetAffinity
omrthread_monitor_init(&monitor, 0)
omrthread_create_ex(&thread, J9THREAD_ATTR_DEFAULT, 0, numaSetAffinityThreadMain, &data)
omrthread_numa_get_node_affinity(omrthread_self(), &currentAffinity, &nodeCount)
Setting thread numa affinity to 2
Failed to set affinity to 2
createTest.cpp:1046: Failure
Value of: status
  Actual: 262144
Expected: (uintptr_t)0
Which is: 0
Failed with Code: 40000
[0;31m[  FAILED  ] [mThreadCreateTest.NumaSetAffinity (0 ms)
[0;32m[ RUN      ] [mThreadCreateTest.NumaSetAffinitySuspended
omrthread_create_ex(&thread, J9THREAD_ATTR_DEFAULT, 1, numaSetAffinitySuspendedThreadMain, &data)
Setting thread numa affinity to 2
omrthread_numa_get_node_affinity(thread, &expectedAffinityBeforeStart, &nodeCount)
omrthread_monitor_enter(monitor)
omrthread_monitor_enter(monitor)
omrthread_numa_get_node_affinity(omrthread_self(), &currentAffinity, &nodeCount)
Affinity different from expected. Expected:2 Actual:1
omrthread_monitor_notify_all(monitor)
omrthread_monitor_wait(monitor)
createTest.cpp:1160: Failure
Value of: status
  Actual: 262144
Expected: (uintptr_t)0
Which is: 0
Failed with Code: 40000
[0;31m[  FAILED  ] [mThreadCreateTest.NumaSetAffinitySuspended (1 ms)

**Comment by DanHeidinga** [comment]
If the test is flaky, it can be excluded by modifying the .travis.yml.  The existing exclude is:  
`- export GTEST_FILTER=-*dump_test_create_dump_*`
The new one should be:
`- export GTEST_FILTER=-*dump_test_create_dump_*,*NumaSetAffinity,*NumaSetAffinitySuspended`

**Comment by DanHeidinga** [comment]
Actuallhy, the ',' should be ':'.  Preparing a patch

**Comment by alin00** [comment]
The numa tests have been solid in our production environment (as have the dump tests, I believe). It's a little unfair to characterize them as "flaky" when it's the playing field that's changed.

**Comment by DanHeidinga** [comment]
Sorry, flaky in the travis.ci environment

**Comment by DanHeidinga** [comment]
Build to ensure that the tests are disabled by the filter in previous comment: https://travis-ci.org/DanHeidinga/omr/builds/117552007

**Comment by mstoodle** [comment]
Any theories for why it would be flakey in the travis.ci environment?

**Comment by alin00** [comment]
@DanHeidinga discussed the dump tests in #20. We haven't investigated the NUMA failures yet.

**Comment by DanHeidinga** [comment]
I've added pull request #28 to disable the tests on travis.
