### ISSUE TITLE
Is branch preloading for calls needed for Z?

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2169]
There is some disabled code on Z for instruction prefetching calls and branch targets (guarded by `supportsBranchPreloadForCalls()`).  Is this just an experiment?  Can the code it enables be removed in Eclipse OMR if it is no longer useful?  @fjeremic

**Comment by fjeremic** [comment]
We've been tinkering with this as of late. For the time being prefetching in general is not buying us anything because of the way the hardware handles software prefetches. There is an excellent summary by Kevin Shum on branch preloads in z/Architecture [1] on page 32.

In summary the current hardware design is to ignore software prefetches in the first level branch target buffer if there is already an entry for the particular branch in question. As far as the Z codegen in OMR a very large percentage of calls will be emitted with `BRASL` instructions, which are direct branches always predicted taken. 

On page 13 in [1] there is a listing of branch prediction resources in the latest processors (bar z14). The branch prediciton tables have quite a lot of resources. For example the first level branch target buffer can hold 1024x6 entries on z13 and the level two can hold 16384x6 entries. Given the large table sizes and the fact that most call instructions are predicted taken ahead of time prefecting calls is in my opinion not worth doing.

We could potentially see a net win for highly polymophic call sites but the issue here is greatly summarized on the best practices on page 32. Here the best practices state that at minimum the target branch for a preload should be more than 1 taken branch away and at least 256 sequential bytes away. On average Z instructions are 4-5 bytes in length so we are talking on the order of ~60 instructions away. This means for polymorphic call sites we would have to preload a branch much earlier which is not always feasible. And only then we have to hope the hardware will respect our decision.

@joransiu is anything missing here?

[1] https://www.ibm.com/developerworks/community/files/form/anonymous/api/library/ff4563be-756e-49bf-9de9-6a04a08026f1/document/3dff8d34-fcf9-4939-9efc-11f15a3ce0f8/media/IBM%20z%20Systems%20Processor%20Optimization%20Primer.pdf

**Comment by joransiu** [comment]
@fjeremic : that's a good summary of the challenges of exploiting Branch Preloads on Z in its current hardware implementation.  Majority of software preloads are not used as there is an existing prediction entry in BTB1.  There is still the indirect benefit that the preload would initiate an i-cache fetch.

While the code is not active, this is a topic that we evaluate with each successive generation of Z hardware design.  I'd prefer we keep the code.

**Comment by 0xdaryl** [comment]
Thanks for the detailed reply @fjeremic.  There's a lot of useful information in that deck.

I'm fine with leaving that code around if you think it may have future applicability to Z.  I thought it was worth asking the question because it appears to have been disabled for many years and there's little documentation on what it's doing.
