### ISSUE TITLE
SPDX-License-Identifier text in file header needs to be refined

### ISSUE THREAD

**Issue by mstoodle** [eclipse/omr#2172]
In #1596 we updated our license according to the directions we were given from the Eclipse Foundation. There has bee, however, and update to the SPDX identifier we should be using to make our license more precise.

We've been asked to update this line in every copyright header to the following:

```
SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
```

Hopefully, this will be the last time we'll need to do this, as it will require a commit that touches basically every file in the repository :( .

**Comment by fjeremic** [comment]
On a related note do we have a script that does this copyright change? If so we should check this into the repository so it is easy to do this next time.

**Comment by pshipton** [comment]
It should be a simple search and replace, but due to the 72 column line limit restriction on z assembler files, these files need to be handled specially. Or the new identifier needs to be broken into multiple lines for all files. For OpenJ9 I fixed the z assembly files by hand since there aren't that many.
