### ISSUE TITLE
Enable automatic pull request copyright checks

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2254]
Re-purpose the copyright checker tool from Eclipse OpenJ9 as part of the Eclipse OMR delivery process.  This will be far more convenient and less error-prone than manually inspecting each file on delivery.

Eclipse OpenJ9 PR that introduced the copyright checker:  https://github.com/eclipse/openj9/commit/ac8ac21a333a863cc928928fd7168e6763351e3b

Some input from @charliegracie specific to Eclipse OMR:

> I think the copyright checker needs some improvements though.  There is a lot of third party files in OMR that do not meet the copyright check.  If we modify that code I do not want the check to fail.  The script needs to be updated to whitelist the thirdparty folder or something similar.

**Comment by 0xdaryl** [comment]
@nbhuiyan

**Comment by AdamBrousseau** [comment]
Are we open to the option of pulling the OpenJ9 Jenkins File directly and making any changes/improvements there rather than committing a ~duplicate script to OMR and having to maintain multiple copies? This is what I did for the OpenJ9 extensions repos.
We could likely come up with a process to pass a whitelist to the script rather than hardcoding multiple whitelists in the same file for each repo.

**Comment by charliegracie** [comment]
I am not sure that is the right answer.  That puts a circular dependency on the projects that does not exist right now.  Currently OpenJ9 depends on OMR and not the other way around.  I think we should think about it a bit more before we make that decision.

**Comment by AdamBrousseau** [comment]
I agree it is not the perfect solution, but neither is code duplication. I don't really want to suggest a "third party tools repo" but I suppose that is an option. It might be a case of the lesser of ~two~ three evils?

**Comment by 0xdaryl** [comment]
I agree with @charliegracie that OMR depending on a downstream project isn't the right answer.  Downstream projects already have a dependence on the upstream OMR.  Perhaps creating a separate tools repo under the Eclipse OMR project for shared infrastructure for runtime projects is the way to go.

**Comment by mstoodle** [comment]
Could OMR be the source and OpenJ9 consumes it from OMR?

**Comment by xliang6** [comment]
> We could likely come up with a process to pass a whitelist to the script rather than hardcoding multiple whitelists in the same file for each repo.

Can we generalize the script to take in repo-specific information like a whitelist filename? If so, this generalized script can reside in OMR. We can then create smaller scripts to call this script with the right filenames for OMR and OpenJ9, or maybe we can achieve this with Jenkins?

**Comment by AdamBrousseau** [comment]
related eclipse/openj9#1043

**Comment by AdamBrousseau** [comment]
FYI, the copyright script now accepts a simple whitelist file `.copyright_whitelist`. If OMR wanted to setup PR check jobs you could pull the script from OpenJ9 and have a file in in the OMR repo that listed all the files to ignore.

**Comment by 0xdaryl** [comment]
@AdamBrousseau, by "pull" do you mean clone OpenJ9 and grab the script from there?  As suggested in some of the discussion above, it might make more sense for the script to live in OMR (as it is already cloned in OpenJ9) rather than the other way around.

**Comment by AdamBrousseau** [comment]
Yes pull from OpenJ9. Keep in mind it isn't a full clone its a lightweight checkout of the single script file. IMO it should be in a generic tools repo but we don't have that right now. Putting it in one of the repos means the other repo has a "dependency" on it. I don't think the argument "OpenJ9 is downstream of OMR" matters because we're just pulling a single file for tooling purposes which has nothing to do with project dependencies. If we were to move the script to OMR it would create just as much of a dependency for OpenJ9 on OMR that IMO technically doesn't currently exists as it is a tooling dependency not a project/source dependency.

**Comment by AdamBrousseau** [comment]
I think ideally we could contribute this to eclipse and have them run it. We could make it more generic to support any copyright and it could probably be expanded to check the license portion of the header too.
