### ISSUE TITLE
How to best handle dependent changes from downstream consumers

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#2303]
As part of https://github.com/eclipse/omr/pull/2302#issuecomment-364489477 the contributor has signaled to the committers that they want the PR to be eligible for merging only after ~an upstream~ downstream dependency has been approved (pending OMR review of course). Our current process for dealing with this is to request the PR be marked "WIP: " (Work In Progress) until a time where the contributor believes it is ready for final reviews and merging.

In https://github.com/eclipse/omr/pull/2302#issuecomment-364492670 the contributor identified this may be a cause of churn as it could delay reviews of the OMR PR. In my opinion I don't think we should liberally be taking advantage that some of the OMR committers are also committers on the ~upstream~ downstream project as that creates coupling and bias towards a particular consumer of OMR. Is there a better way to handle these situations?

**Comment by dmitripivkine** [comment]
In my opinion OpenJ9 is not a upstream but downstream project. The change itself would not break OMR but OpenJ9 might be broken. This fact of such dependence has been reflected in PR and committer has to be noticed. WIP however might be used for dependent OpenJ9 item.
Also I believe it is a good practice to submit both PRs at the same time to minimize time dependent project is broken.

**Comment by 0xdaryl** [comment]
I am of the opinion that the contributor of a change that may involve multiple projects should assume the bulk of the responsibility for shepherding it into the codebase(s).  Yes, an OMR committer ultimately has to push the OMR button after ensuring adequate reviews are complete and that the contributor guidelines are being followed, but staging a delivery across OMR and a downstream project should really be orchestrated by the contributor in my opinion.  This starts with the code itself and ensuring it is written in a staged manner that doesn't rely on coordination.  I'll concede there are situations where this isn't possible, but there have been examples in the past where it *was* possible but not done for whatever reason leading to downstream churn.

In my mind, the WIP scheme is simple and does the job we want it to do.  Namely, it allows the contributor of a PR to hold back the committers from merging until they have made all downstream preparations (e.g., ensuring a dependent PR is merged) or for any other reason for that matter.  A contributor can (and should) use the comment section of their own PR to explain their unique circumstances for merging (e.g., requesting a review even though it's marked WIP, informing a committer of their desire to coordinate when the PR is merged, etc.), and all OMR committers are willing to work with contributors and have demonstrated they are responsive to their requests.  Communication is key.  There are numerous examples of this over OMR's two year history.

Eclipse OMR is a project independent from OpenJ9 (and *any* downstream project for that matter) and needs to maintain that independence if it's going to be successful.  If OMR becomes as ubiquitous as we are working to make it then introducing a downstream dependency mechanism isn't likely to work at scale across many projects.  For example, what if some feature is contributed to OMR that has a dependency on multiple downstream projects X, Y, and Z that all want to consume it.  Projects X and Z want to consume the feature, but project Y isn't ready yet.  Do we not merge the PR because of potential churn in Y?

Addressing the original reason this issue was created, the Eclipse OpenJ9 project actually has a mechanism for ensuring dependent OMR and OpenJ9 changes get merged together by the same OpenJ9 committer, causing minimal churn to the OpenJ9 project while reviews and merging proceed in Eclipse OMR.  The OpenJ9 project maintains an "openj9-omr" repo where urgent OMR changes can be committed if merging delays from the upstream OMR project cannot be tolerated.  It was created for exactly this reason.  This happens internally to the OpenJ9 project, which is exactly where it should be handled in my opinion.

Furthermore, if a downstream project wants to take advantage of the fact that an Eclipse OMR committer is also a committer in that project and you want them to coordinate the merges then that should fall under the commit policies of that downstream project rather than Eclipse OMR.

**Comment by mstoodle** [comment]
One of the aspects of the Eclipse OMR project right now that makes this problem a bit more of a pain than it really should be is that we haven't been doing OMR releases.

It's not a panacea because not all components that the downstream Eclipse OpenJ9 project depends on have stable APIs in Eclipse OMR yet (e.g. compiler). We will still have to deal with this kind of thing, and (I would guess) downstream projects will still want to discover possible breakage as early as feasible, but hopefully it's a path towards a better steady-state model for how these things should happen.

Please see #2274 for the current Eclipse OMR proposal and provide feedback there if anyone has input or concerns!
