### ISSUE TITLE
Agenda for April 27, 2018 OMR Compiler Architecture Meeting 

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2422]
### Agenda

1.  OMR initialization process (#1644 ) [ @0xdaryl  ]

### Details
Friday, April 27, 2018 @ 11:00 EDT (GMT -4), 60 minutes maximum

Join [Webex](https://ibm.webex.com/ibm/e.php?MTID=mf1a9119dee61d726785731bc791b6d47)

Meeting number (access code): 926 451 089
Meeting password: omrrocks!

[Global call-in numbers (for audio only)](https://ibm.webex.com/cmp3200/webcomponents/widget/globalcallin/globalcallin.do?siteurl=ibm&serviceType=MC&eventID=650956722&tollFree=1)

**This meeting will be recorded and posted to the [Eclipse OMR YouTube channel](https://www.youtube.com/channel/UCO8MkTRrFnLefi5nqReOMMA).**

**Comment by 0xdaryl** [comment]
We had a discussion on the OMR initialization process that was driven by the compiler's desire to be included as part of the general OMR component initialization method `OMR_Initialize_VM`.  This is because the compiler technology is now dependent on the port library (and thread library by transitivity) and it seemed like a more natural place to perform initialization of the compiler technology.

One challenge with `OMR_Initialize_VM` was that it required further dependencies on OMR components that were not expected (e.g., Healthcenter, RAS).  However, upon discussion it was revealed that there are build flags available for guarding access to those components and the appropriate code in the initialize method simply needs to be wrapped with them.  This work was completed in #2580.

There was some discussion around the unique initialization requirements of the compiler technology and the current requirements of the `OMR_Initialize_VM` API.  In particular, the compiler (or JitBuilder) technology would have to provide an `OMR_VM` (a VM-wide convenience structure from which many VM data structures can be reached) and an `OMR_Thread` structure (a structure that encapsulates per-thread data) which neither technology currently uses.  The discussion focused on what the minimum set of information is needed to initialize the compiler, and whether providing these two structures was really necessary (e.g., could you pass in NULL instead and could the initialization code handle it?).

For the compiler technology (and JitBuilder in particular) there seem to be two use cases:
1) As a native acceleration library.  In this scenario, JitBuilder isn't being used as a JIT per se but more like a library to generate native code.  It may not make sense to force initialization of this library into the overall initialization process of the VM.
2) As a JIT in a runtime.  In this case it makes more sense to include its initialization as part of overall OMR initialization.

@mstoodle stressed the requirement that JitBuilder initialization be straightforward as that is one of its principal design points.

@rwy0717 then described some of the refactoring work he has done in the OMR initialization functions to support developing OM (a new object model "builder"), and the group discussed the applicability of that design to the broader OMR initialization for larger runtime integration.  We agreed that initialization could be partitioned into distinct tiers:
1.  Process-wide initialization.  This would be used to initialize port and thread.
2.  VM startup initialization.  Used to initialize components such as the compiler and GC.
3.  VMThread startup initialization.  Bring up thread-local contexts (e.g., GC threads, compiler threads).

The initialization would occur in that order.  It can also be thought of as:  a process for a runtime is created, then one (or more) VMs attach to that runtime process, and then one (or more) threads are attached to those VMs.

When components (like JitBuilder) are to be used as a library, we agreed it would still be useful to provide a simplified interface (like `initializeJit()` or perhaps more generically `initializeLibrary()`) that can be called that will take care of the initialization steps in that context.  For example, it would be responsible for either initializing (or finding) a port library to use within JitBuilder.

We concluded with a discussion on Option processing and how (at least in the case of the compiler code in OpenJ9) it is woven through the initialization steps and how a cleaner design is preferred and needs to work in the 3-tiered model.

**ACTION**: @nbhuiyan to use build flags to isolate components in `OMR_Initialize_VM` to break unnecessary dependencies.  Done in #2580.

**ACTION**: @rwy0717 / @nbhuiyan to create an issue proposing a design for the 3-tiered initialization model.

**ACTION**: @nbhuiyan to add thread and port library initialization to JitBuilder and Test compiler `initializeJit()` functions.

**ACTION**:  @0xdaryl to create an initial design for compiler option processing.

**Comment by charliegracie** [comment]
I have a couple of questions / comments....
1. maybe the compiler architecture meeting should turn into an OMR architecture meeting.  There seem to be a lot of out reaching discussions happening that should probably include a larger audience than just folks interested in compiler technology.
2. Does the JitBuilder technology have any global state that it keeps?  If so that should be tracked off of the OMR_VM.
3. If the JitBuilder technology is being used in a threaded environment where you have more than one compilation thread do you see there being per thread information required by the compiler?  If so the compiler / JitBuilder will need to have per thread information which should be stored off of the OMR_VMThread.  
4. JitBuilder should NOT startup its own port or thread library. What happens if you are using JitBuilder in a runtime with the GC and RAS, etc.? All of these components need a port and thread library.
4.1 Do you want that runtime to have to start up all of these components individually in the correct order? 

The current startup and shutdown API has existed in some form or another since before the compiler and JITBuilder technology existed in the project.  Of course there are some wrinkles that need to be worked out but a standard set of APIs to bring up the runtime makes sense and should not be abandoned or worked around.

In the current actions I strongly disagree with the initializeJit() function starting up the Port and thread libraries.  The initializeJIT function should take an OMR_VM as a parameter and fetch the port library / thread library out of there. In the case of accelerators they would still startup the first two tiers in the new 3 tier model that is being discussed so it works perfectly.  

As the OMR project moves forward we will see more and more uses for the OMR_VM and OMR_VMThread.  These should be the starting point for any "global" type data.
