### ISSUE TITLE
Early allocation of CodeCacheHashEntrySlab

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2470]
I'm trying to understand this comment:

https://github.com/eclipse/omr/blob/2f938a7b9ac34708a16ae170bc92157eed944fb1/compiler/runtime/OMRCodeCache.cpp#L1697-L1698

I'm considering sinking that allocation down to where it actually needs to be as part of some broader work on trampolines (rather than allocating it before the code cache and then passing it down as a parameter), but I'm cautious about the implications and side effects.  That comment is from shortly after Testarossa's Planck Epoch, so I'm not sure if its message is still correct or relevant.

From reading the code, I believe the reason the allocation is done earlier (i.e., here) is because:
1)  If the allocation fails there's no point in even attempting to allocate the code cache because it will also fail.  Hence, this is a quicker way to determine allocation failure, and move on.
2)  If there is an allocation failure during code cache creation (which involves several functions), it will be easier to de-allocate the `CodeCacheHashEntrySlab` on failure in this function.

I don't believe 1) is really an interesting path to be optimizing, and I'm not convinced that 2) is really a complicated scenario that can't be easily solved.

Do any of the other grey beards have a better recollection on why this allocation happens here and the implications of sinking it?

@zl-wang @mpirvu @mstoodle

**Comment by mpirvu** [comment]
That's exactly how I interpret the comment as well (I don't remember to have written that comment).
If the slab is allocated later we must be careful with exposing the newly created code cache to the outside world as it it not fully initialized (the slab is used in `codeCache->initialize()`. I believe that once you attach it to global list with `manager->addCodeCache(codeCache)` it's up for grabs, though marking it as `reserved` prevents other parties from being interested in it.

**Comment by mstoodle** [comment]
Like @mpirvu , I do not recall the actual reasons, but from glancing at the code it does appear that quite a bit of stuff happens in the initialization of an allocated code cache, including updating at least one field in the manager object. I also wonder if deallocation could be guaranteed not to "interfere" with another thread allocating a code cache at the same time from the repository (i.e. leaving a gap that the repository would then need to manage).

There currently isn't a `deallocateCodeCacheObject()`, but it would need to be kept in sync with any code updates to `initialize()` which may have been deemed less attractive than simply allocating two objects in one order rather than the other way around. 

Is there some natural ordering that suggests the code cache should really be allocated before the hash entry slab?

**Comment by zl-wang** [comment]
No, there is no better recollection.  You described the motivations correctly (there were a few failure returns originally. Avoiding the relatively expensive initialization only to find you are failing for the relatively cheaper [smaller] allocations.)

**Comment by mstoodle** [comment]
Actually, the code cache segment is also allocated (right!) before even the hash entry slab, so my argument about allocate/deallocate risk doesn't hold much water (we already do "uncarving" from the code cache repository in that case).

**Comment by zl-wang** [comment]
yes, it is that way with code cache repository (reserved memory).  it was not that way in the past: codeCache data structure and code cache segment were allocated separately.
