### ISSUE TITLE
Add OMR coding standard

### ISSUE THREAD

**Issue by alin00** [eclipse/omr#25]

**Comment by mstoodle** [comment]
Thanks, Angela, it looks really good. I'll track down the CQ issue as I mentioned in the merge request.

I'd like to leave this issue open for a few days at least so everyone can discuss the coding standard being introduced. If there's no discussion or the discussion dies down, we can close this issue but this document is expected to evolve over time so real concerns that arise can always be raised for discussion via new issues.

**Comment by lmaisons** [comment]
I took a look at the style guidelines, a few things stuck out:

In C code, variables must be declared at the top of a scope. In C++ code, variables may be declared anywhere inside a scope. Although some C compilers may allow variables to be declared throughout a scope, some do not (e.g. MSVC).

All code is written to ISO/ANSI rules for C99 ISO C compilers.
==> Seems to contradict; did we mean ANSI C89 / ISO C90?

In function arguments, temporary variables, and class data members, mark pointers as ```const``` if the data will only be read.  ```const``` establishes an official contract between the caller and the callee. The compiler can validate that this contract is followed.

==>  I found this wording somewhat ambiguous given the examples that followed it, a const pointer is usually ```Type * const var;``` but the examples use pointers to const values ```const Type * var;```.  I, myself, would find it useful if the wording were changed to match the intent expressed in the example.

All objects and structures should be passed by address (i.e. *) rather than reference or value.
Non-object parameters that are not updated should be passed by value. C++ reference (i.e. &) arguments must not be used.
Rationale: Reference arguments can be problematic. For example, it's impossible to pass NULL for a reference object. They're just syntactic sugar to hide pointers, so we prefer to be explicit about how the argument is being passed.

==> C++ References enforce the equivalent of a non-NULL const pointer which is a stronger contract than merely declaring the pointer const.  Furthermore, it helps disambiguate the meaning of const and volatile in declarations.  Generally, modern C++ strongly attempts to eschew pointers as much as is reasonably possible, passing by value or const reference whenever it can, passing by reference when needed.  Pointers are considered to obfuscate ownership and resource management responsibilities.  The community has even gone so far as to produce a ```reference_wrapper``` class to be able to maintain (as far as possible) the conceptual integrity and  non-nullable nature of references while being able to use them in container classes.  For an example of this sentiment, see the 'no raw pointers' goal in well-received talk by Sean Parent on 'C++ seasoning'.

==> Further to the subject above about const pointers, whenever possible, I find it useful to make all non-index variables, especially all passed parameter values, const. In the case of pointers, the pointer itself is marked const: ```SomeType * const``` (possibly in addition to the pointed to type). This is somewhat stricter than what's requested here, but in light of the discipline desired in other parts of the style guide, this feels like it might fit.

The increment and decrement operators (++ and --) are discouraged. Use += or -= instead. 
EXCEPTION: ++ may be used in for loops, as this is a pervasive idiom.
==> Should we limit this to / strongly prefer the prefix unary operators? ++iterator rather than iterator++

Nor can we rely on the presence of C++11 features.
==> TR already depends on decltype and auto.  Ideally we would want to use more C++11 features in the future when we get support on on all of our supported targets.

Indent the parameter list by at least 1 tab. Where reasonable, the parameter list should be aligned with the opening bracket.
==> Why isn't indenting by 1 tab sufficient?  Isn't this mixing indentation and alignment?

Do not use a comment to disable a section of code. Instead, use #if 0/#endif.
==> I'm sort-of surprised we want disabled code at all.

Member variable names should start with an underscore: e.g. ```_heapSize``` (C++ only)
==> There seems to be a consensus in the community that this is a bad idea and that instead something along the lines ```m_heapSize``` should be used instead of just a raw underscore.

Enum definitions exposed outside of a single file must include a dummy member with a large value to force the enum to be represented using at least 4 bytes. (If there is doubt about the visibility of the enum definition, include the dummy member.)
==> How does this change for strongly typed enums in C++11?  Also from what I recall, this can make compilers (Clang++ I think) cranky when dealing with switch statements, though the style requirement for default cases probably mitigates most / all of that crankiness.

==> MISSING: MSVC needs all class-key declarations (struct, class, union) for a particular typename to be consistent as it uses the class-key as part of name-mangling.

**Comment by alin00** [comment]
Hi Luc,

It would be easier to have threaded conversations about specific points if you made line comments on the commit. (Unfortunately, that would tie the conversation to the pull request, and not the issue, I believe.)

I am happy to make clarifications to the document. However, changes of substance should probably be voted on by all committers, or some such process.

> In C code, variables must be declared at the top ...

I didn't see a comment from you on this.

> All code is written to ISO/ANSI rules for C99 ISO C compilers.
> ==> Seems to contradict; did we mean ANSI C89 / ISO C90?

I will correct this to "All C code is written to rules for C99 compilers." That begs the question, then, of which C++ standard do we follow: we've never actually decided.

> In function arguments, temporary variables, and class data members, mark pointers as const if the data will only be read. const establishes an official contract between the caller and the callee. The compiler can validate that this contract is followed.
> 
> ==> I found this wording somewhat ambiguous given the examples that followed it, a const pointer is usually Type * const var; but the examples use pointers to const values const Type * var;. I, myself, would find it useful if the wording were changed to match the intent expressed in the example.

I suspect there are folks who would misunderstand the phrase "pointer to const value", but I agree it more accurately reflects the intent of the rule. Here is the correction:

> In function arguments, temporary variables, and class data members, pointers to data that will only be read should be defined as pointers to `const` values.
> ...
> * Use of `const` may allow greater optimization.

> All objects and structures should be passed by address (i.e. *) rather than reference or value.
> ...
> ==> C++ References enforce the equivalent of a non-NULL const pointer which is a stronger contract than merely declaring the pointer const. ...

I suggest you open a separate issue to discuss this topic.

> ==> Further to the subject above about const pointers, whenever possible, I find it useful to make all non-index variables, especially all passed parameter values, const. In the case of pointers, the pointer itself is marked const: SomeType * const (possibly in addition to the pointed to type). This is somewhat stricter than what's requested here, but in light of the discipline desired in other parts of the style guide, this feels like it might fit.

This is good advice, but does feel a bit strict. I think this is not codified because we haven't encountered enough scenarios where not following this practice caused bugs. Feel free to open a separate issue to discuss this topic, as well.

> The increment and decrement operators (++ and --) are discouraged. Use += or -= instead. 
> EXCEPTION: ++ may be used in for loops, as this is a pervasive idiom.
> ==> Should we limit this to / strongly prefer the prefix unary operators? ++iterator rather than iterator++

Since we discourage the unary operators, it doesn't seem to make sense to discourage one less than the other. The performance difference between them is usually not significant.

> Nor can we rely on the presence of C++11 features.
> ==> TR already depends on decltype and auto. Ideally we would want to use more C++11 features in the future when we get support on on all of our supported targets.

Is the JIT (TR) code you're referring to platform-specific?

I think requirement of C++11 features would unnecessarily limit the portability of OMR. The compilers we use for some products that consume OMR don't support C++11. 

> Indent the parameter list by at least 1 tab. Where reasonable, the parameter list should be aligned with the opening bracket.
> ==> Why isn't indenting by 1 tab sufficient? Isn't this mixing indentation and alignment?
 
Ah, my least favourite recent addition to the coding standard. :) 

Alignment with the opening bracket was a very strong style preference of the original advocate for this rule. We compromised by weakening the alignment rule to "where reasonable" and "should".

> Do not use a comment to disable a section of code. Instead, use #if 0/#endif.
> ==> I'm sort-of surprised we want disabled code at all.

It's sometimes reasonable to leave in disabled debugging code or WIP code.

> Member variable names should start with an underscore: e.g. _heapSize (C++ only)
> ==> There seems to be a consensus in the community that this is a bad idea and that instead something along the lines m_heapSize should be used instead of just a raw underscore.

We'll need a committer vote on this. Please open a separate issue.

> Enum definitions exposed outside of a single file must include a dummy member with a large value to force the enum to be represented using at least 4 bytes. (If there is doubt about the visibility of the enum definition, include the dummy member.)
> ==> How does this change for strongly typed enums in C++11? Also from what I recall, this can make compilers (Clang++ I think) cranky when dealing with switch statements, though the style requirement for default cases probably mitigates most / all of that crankiness.

I don't know. We got bit when we dropped this rule for a while. Do C++11 compilers still have discretion to choose the width of enums? Do you have an alternative solution?

> ==> MISSING: MSVC needs all class-key declarations (struct, class, union) for a particular typename to be consistent as it uses the class-key as part of name-mangling.

This was never codified because we didn't encounter this problem. You can propose this addition - open another issue.

Thanks for the comments!

**Comment by lmaisons** [comment]
>     In C code, variables must be declared at the top ...
> 
> I didn't see a comment from you on this.

Sorry, I meant to tie that requirement, which includes the rationale `C89 compilers require all variables to be declared at the top of a scope.` with the following one about C99.

>     Nor can we rely on the presence of C++11 features.
>     ==> TR already depends on decltype and auto. Ideally we would want to use more C++11 features in the future when we get support on on all of our supported targets.
> 
> Is the JIT (TR) code you're referring to platform-specific?
> 
> I think requirement of C++11 features would unnecessarily limit the portability of OMR. The compilers we use for some products that consume OMR don't support C++11. 

In JIT code, decltype and auto have no platform restrictions, as -std=c++0x and its equivalents supported their use on all the compiler / platform combinations we built against.



>     Enum definitions exposed outside of a single file must include a dummy member with a large value to force the enum to be represented using at least 4 bytes. (If there is doubt about the visibility of the enum definition, include the dummy member.)
>     ==> How does this change for strongly typed enums in C++11? Also from what I recall, this can make compilers (Clang++ I think) cranky when dealing with switch statements, though the style requirement for default cases probably mitigates most / all of that crankiness.
> 
> I don't know. We got bit when we dropped this rule for a while. Do C++11 compilers still have discretion to choose the width of enums? Do you have an alternative solution?

C++11 [apparently](http://stackoverflow.com/questions/12125637/can-i-define-the-size-of-an-enum-in-c) overloads the inheritance syntax to allow enum declarations to explicitly determine their size.

I'll also open new issues for the other items as suggested.

Thanks!

**Comment by alin00** [comment]
If I look at some XL C/C++ doc, like this one: http://www.ibm.com/support/knowledgecenter/SSLTBW_2.2.0/com.ibm.zos.v2r2.cbcux01/lnglcop.htm

... It says that support for C++11 features is still evolving, and may not be stable from release to release. This makes me hesitant to rely on them.

**Comment by mgaudet** [comment]
> C++11 apparently overloads the inheritance syntax to allow enum declarations to explicitly determine their size.

Unfortunately, last I checked not all the compilers we would want to use support this particular part of C++11 yet. Ditto strongly typed enums.

**Comment by lmaisons** [comment]
> If I look at some XL C/C++ doc, like this one: http://www.ibm.com/support/knowledgecenter/SSLTBW_2.2.0/com.ibm.zos.v2r2.cbcux01/lnglcop.htm
> 
> ... It says that support for C++11 features is still evolving, and may not be stable from release to release. This makes me hesitant to rely on them.

This is probably worth a wider discussion with JIT contributors.  I don't know all the specifics that went into making the decision to OK using the C++11 features that we do.  What I do remember is that each time we've changed our canonical build compilers, we've first verified that they supported our code base, rather than assuming each version increase supported a strict super set of the previous versions.

> 
> > C++11 apparently overloads the inheritance syntax to allow enum declarations to explicitly determine their size.
> 
> Unfortunately, last I checked not all the compilers we would want to use support this particular part of C++11 yet. Ditto strongly typed enums.

You're right, and honestly, this is probably jumping the gun at this point.  While I was reading the guidelines, I was reminded of compiler warnings about uncovered switch cases, that in-turn reminded me of the (lack of) type safety in enums and enum classes.  In the end I probably conflated the issues more than I should have.

**Comment by mstoodle** [comment]
Please open the remaining discussion items as separate issues. The fact that the issue was closed (because I merged the coding standard document) does not mean the discussion needs to stop! It just enables us to discuss more fruitfully as separate issues / pull requests.
