### ISSUE TITLE
Agenda for July 18, 2018 Compiler Architecture Meeting

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2765]
### Agenda

1.  Discuss removing usage of C++ STL from the compiler [ @mstoodle ]

[Meeting Replay](https://www.youtube.com/watch?v=RVGql8xZhh8)

### Details
Wednesday, July 18, 2018 @ 13:00 EDT (GMT -4), 60 minutes maximum

Join [Webex](https://ibm.webex.com/ibm/j.php?MTID=m9677a588b7f8180c62813ac3e620fb28)

Meeting number (access code): 927 085 394
Meeting password: omrrocks!

[Global call-in numbers (for audio only)](https://ibm.webex.com/cmp3300/webcomponents/widget/globalcallin/globalcallin.do?siteurl=ibm&serviceType=MC&eventID=706433492&tollFree=1)

**This meeting will be recorded and posted to the [Eclipse OMR YouTube channel](https://www.youtube.com/channel/UCO8MkTRrFnLefi5nqReOMMA).**

**Comment by dibyendumajumdar** [comment]
Hi @mstoodle,

I would have liked to join in this discussion but couldn't due to other engagements. Just wanted to say that it seems common for custom containers to be used in compiler projects. I think LLVM has them. Also Webkit's JavaScript JIT uses custom implementations.

Regarding sources of STL like implementations: 
* https://github.com/WebKit/webkit/tree/master/Source/WTF/wtf
* https://github.com/bloomberg/bde/wiki/BSL-and-STL

Although I am not sure I would recommend replacing the existing implementations, as you probably will need to pull in a quite a lot of the stuff from any external library (and I would hate the code base to grow in size, from a selfish point of view).

Also no harm in using STL internally - but I think not exposing allocators to users is a VERY good idea!

**Comment by dsouzai** [comment]
@nwoeanhinnogaehr came up with a way of not requiring one to specify the allocators when initializing STL containers, for example:

```
template<typename T>
using PersistentVectorAllocator = TR::typed_allocator<T, TR::PersistentAllocator&>;
template<typename T>
using PersistentVector = std::vector<T, PersistentVectorAllocator<T>>;
```

**Comment by Leonardo2718** [comment]
I think this solution has been attempted already and, very unfortunately, templated using declarations (a C++11 feature) are not supported by all our supported build compilers .
