### ISSUE TITLE
omrsigcompat fails to load Microsoft Visual C++ library

### ISSUE THREAD

**Issue by babsingh** [eclipse/omr#2904]
In [omrsig_internal.hpp:88](https://github.com/eclipse/omr/blob/master/omrsigcompat/omrsig_internal.hpp#L88), `MSVC_RUNTIME_DLL` is defined as:

```
#define MSVC_RUNTIME_DLL "MSVCR100.dll"
```

[omrsig.cpp:omrsig_signalOS_internal](https://github.com/eclipse/omr/blob/master/omrsigcompat/omrsig.cpp#L348) fails to load **MSVCR100.dll** if compiled with other than Visual Studio 2010:
```
signalOS = (SIGNAL)GetProcAddress(GetModuleHandle(TEXT(MSVC_RUNTIME_DLL)), "signal");
```

CMake build files ([omrsigcompat/CMakeLists.txt](https://github.com/eclipse/omr/blob/master/omrsigcompat/CMakeLists.txt#L55)) set `MSVC_RUNTIME_DLL` during compilation:
```
target_compile_definitions(omrsig PRIVATE -DMSVC_RUNTIME_DLL="${OMR_MSVC_CRT}")
```

`OMR_MSVC_CRT` is set by CMake build files here: [cmake/modules/OmrMsvcRuntime.cmake](https://github.com/eclipse/omr/blob/master/cmake/modules/OmrMsvcRuntime.cmake).

But, OpenJ9 doesn't build OMR using CMake yet. [omrsigcompat/makefile](https://github.com/eclipse/omr/blob/master/omrsigcompat/makefile) doesn't set `MSVC_RUNTIME_DLL` during compilation. In OpenJ9, `MSVC_RUNTIME_DLL` is set to **MSVCR100.dll**. When compiling OpenJ9 with VS 12, **MSVCR100.dll** is not found.

Since `MSVC_RUNTIME_DLL` is not set properly, `omrsig_signalOS_internal` fails to function properly on Windows. Due to this, `omrsig` library fails to register OS handlers on Windows.

[omrsigcompat/makefile](https://github.com/eclipse/omr/blob/master/omrsigcompat/makefile) needs to properly set `MSVC_RUNTIME_DLL` depending upon the version of Visual Studio used for compilation.

**Comment by babsingh** [comment]
@rwy0717 any suggestions/recommendations on setting `-DMSVC_RUNTIME_DLL="${OMR_MSVC_CRT}"` in the old build system?

**Comment by rwy0717** [comment]
I would add a new `AC_ARG_VAR` to OMR's `configure.ac` for passing in the name of the DLL. You could call it `OMR_MSVC_CRT`, to match cmake. I would put the result to `omrcfg.h`, and ditch the old define.

You'll also need to update cmake to output the DLL name to `omrcfg.h`, and stop using `target_compile_definitions`.

J9 can set the option manually, maybe through the `configure_includes`. I wouldn't bother trying to guess the MSVC version in the OMR configure script, since it wont work when j9 is cross configuring.
