### ISSUE TITLE
Correctly set node flags for internal pointer in VP

### ISSUE THREAD

**Issue by liqunl** [eclipse/omr#3040]
Internal pointers - aiadd/aladd nodes pointing to the middle of an object should have `isInternalPointer` flag set. Not setting it and its pinning array will result in the evaluator go to a wrong path.

**Comment by jdmpapin** [comment]
I've written a [small test case](https://github.com/eclipse/omr/files/2465040/Repro.java.txt) to expose the incorrect GC map at `arraycopy` in OpenJ9. For me this reliably and promptly (within a few seconds) fails a GC assertion when run as follows:

    $ java -Xjit:'limit={*.go(*)*},count=64,disableAsyncCompilation,disableDynamicLoopTransfer,optLevel=warm' -Xgcpolicy:optthruput -Xms8m -Xmx8m Repro

I haven't been able to cause a crash this way with gencon. Perhaps the arrays are tenured and ignored because global collection is unnecessary? Testing this with optthruput should be fine, though, since there is no difference in which nodes' values are collected references.
