### ISSUE TITLE
New IL Opcode Request: lumul

### ISSUE THREAD

**Issue by hsoontie** [eclipse/omr#3450]
## IL Opcode Name

lumul / long unsigned multiplication

## Motivation

If added, lumul would perform multiplication between two unsigned long integers. 

This opcode is needed because the evaluator that currently exists for long multiplication cannot distinguish whether its input is signed or unsigned from within its own scope, and as it stands, the evaluator is meant to handle both signed and unsigned multiplication. Adding lumul as an opcode would allow a second evaluator to be created alongside lmul to handle unsigned longs seperately, much like the existing imul and iumul.
An alternative would be to give the evaluator function some way of knowing whether its input was signed or unsigned (for example, adding an extra variable to the Node object being passed). This would likely require more overhead to implement, however.

## Homogeneity

This opcode would work in the same way as lmul, with the signed/unsigned format being the only difference. The two would mimic the way imul and iumul work (one for signed, one for unsigned).

#### Data Type

`uint64_t`

#### Children

Would require two 64-bit integers for its operation.

#### Symbol Reference

N/A

#### IL Opcode Properties

The opcode's properties would be similar to those of iumul and imul.

#### Node flags

N/A

#### Control Flow

N/A

## Operation

lumul would perform multiplication between two unsigned long integers.

#### Result Value

Evaluation would produce one result only, and would be as described above.

#### Side Effects

N/A
 
#### Anchoring

N/A

## Scope

There is a reasonable chance of optimization occurring.
This IL opcode will be useful on all code generator backends in Eclipse OMR.
This opcode maps to a machine instruction.

## Implementation Dependencies

* May require implementation in all backends

## Performance

N/A

## Testing Considerations

Tril tests will be developed.

## IL Validation

N/A

**Comment by Leonardo2718** [comment]
> This opcode is needed because the evaluator that currently exists for long multiplication cannot distinguish whether its input is signed or unsigned from within its own scope, and as it stands, the evaluator is meant to handle both signed and unsigned multiplication.

Pedantic: I don't think this is true. Unsigned long integer multiplication is just not supported by the compiler at all.

> ## Homogeneity
>
> This opcode would work in the same way as lmul, with the signed/unsigned format being the only difference.

Probably also worth restating that it matches what is done with `imul` and `iumul`.

> #### Children
>
> N/A

Surely this opcode expects children (two 64-bit integers).

> #### IL Opcode Properties
>
> N/A

I would think the opcode should have properties similar to `lmul` and `iumul`.

> #### Node flags
>
> `is64Bit`

I don't think `is64Bit` is a node flag.

> `lumul` would perform multiplication between two unsigned long integers and store the result in a register.

Pedantic: the opcode wouldn't actually "store" a result, it just emits (returns) a result as a 64-bit integer.

> ## IL Validation
>
> Via tril tests.

This section is supposed to cover special considerations regarding the IL Validator (e.g. special handling in existing validation rules or entirely new rules needed). I believe `lumul` should be covered by the existing rules and won't require any special handling.

**Comment by hsoontie** [comment]
I updated it for clarity. Thank you!
Are there specific points that should be listed under properties, and if so, where may I find them?

**Comment by andrewcraik** [comment]
So I believe `iumul` should be deprecated - an `imul` takes two 32bit integers and multiplies them to produce a 32bit value - the only parts of the operation affected by sign are the high half and flags which is why we need an `imulh` and an `iumulh`. For `lmul` we take two 64bit integer and multiply them to produce a 64bit value. Again the difference is in the high part and flags of the result so I don't think we need the `lmul`. Note that we do not model the flags in the IL - in cases where we would want to care there are the OverflowCHK nodes which would need to modify the evaluation of the appropriate mul to be able to check flags or test the result. Most of the math operations like add and subtract have no signed-ness in the TRIL - they represent a result bit-pattern the interpretation of which is made later either by conversion opcodes or whatever. I believe the same rule applies in this case because the result is a bit pattern open to interpretation I don't believe we need the `lumul` - we may need the `lmulh` and `lumulh` equivalents later if we need to generate the high half of the result or check the result for overflow.

**Comment by Leonardo2718** [comment]
Upon reflection, I think @andrewcraik is correct. Although there is an `iumul` opcode, it should be deprecated because it is equivalent to `imul` (overflow checks are not represented/handled by these opcodes). There is, therefore, no need to make the `lmul` family of opcodes symmetric with the 32-bit counterparts by adding `lumul`.

Closing.
