### ISSUE TITLE
Simplify clearing least-significant 32-bits of a 32-bit extended to 64-bit load

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#365]
The following case is reducible to an `TR::lconst 0` however the case is missing from the simplifier:

```
 n676n    (  1)    land (cannotOverflow)
 n758n    (  1)      iu2l (highWordZero X>=0 unneededConv)
 n525n    (  2)        ==>iloadi (cannotOverflow force64Reg isUnsignedLoad)
 n678n    (  1)      lconst 0xffffffff00000000 (X!=0 X<=0)
``` 

The task here is to add another case to `landSimplifier` in [omr/blob/master/compiler/optimizer/OMRSimplifierHandlers.cpp](https://github.com/eclipse/omr/blob/master/compiler/optimizer/OMRSimplifierHandlers.cpp) to reduce this tree sequence. The change should be made generic enough so that a similar simplification can be carried out for other types such as `TR::iand` and `TR::sand`.

**Comment by fjeremic** [comment]
@andrewcraik If the`n525n` load in the above tree had a reference count greater than 1, would there be any scenario in which this optimization would be possible?

**Comment by Krovatkin** [comment]
@fjeremic , i guess i got quite rusty in TR IL, but i don't understand why multiple uses of the `iloadi` would preclude the optimization you are proposing? Unless the other reference has something to do with a `nullCHK` and folding `land` *somehow* ??? results in removing the `nullCHK`. 
It might swing down though, if this `iloadi` was the first use. 

Or were you more interested if the scenario where `iloadi`'s reference count > 1 occurs in the wild?

**Comment by andrewcraik** [comment]
So I'm a bit curious about that iloadi - a *loadi is an indirect load so there must be a child unless the load has been commoned with an earlier usage. As long as the point of first evaluation for the subtree under the first child does not change (the most conservative thing to do is to just anchor it and leave it to other opt passes to clean it up, more than that and you have to do more checking to make sure that not anchoring really is ok) then you should be fine. As Nick says there are a number of corner cases to consider when you decide not to just anchor - plenty of examples in the transformations in the file you linked to.

You do need to be careful though that you are not making things more complicated by doing the simplification - changing the land to an iand could cause a number of i2l or iu2l conversions to be inserted where the and is being used and can degrade performance because then everyone has to see the conversion and the program as a whole has gotten more complicated.

**Comment by fjeremic** [comment]
@andrewcraik You are correct. I have updated the original tree to reflect exactly what I saw in the log. The `iloadi` was indeed commoned. If I were to anchor the `iloadi` in a `treetop` before the `land` and subsequently replace the entire `land` tree with an `lconst 0` would this be correct?

@Krovatkin This was the case I was thinking of. AFAIK the IL semantics dictate that nodes with symbol references must be evaluated the first time they are seen and if this `iloadi` was the first of many commoned references then completely eliminating it would not be correct as the commoned reference would swing down as you noted. It seems from Andrew's comment that the right thing to do is to just anchor the `iloadi` and then do the optimization. If there are no other uses of the `iloadi` then a subsequent dead trees pass will remove it. This is not the job of the simplifier however.

Thank you both for input!

**Comment by andrewcraik** [comment]
I think for complete correctness you need to anchor the iu2l rather than just the iloadi - someone else could be using the iu2l. If the ref count of the iu2l is 1 then just anchoring the iloadi would be enough. Basically, the point of evaluation should not change for anything to avoid non-local reasoning.
