### ISSUE TITLE
WIP: Porting OMR Compiler to RISC-V

### ISSUE THREAD

**Issue by shingarov** [eclipse/omr#3699]

**Comment by janvrany** [comment]
The code can be found at https://github.com/shingarov/omr/tree/riscv

**Comment by shingarov** [comment]
Initial pull request 3907.
As of today, 32914 TRIL tests pass.

**Comment by janvrany** [comment]
**A brief update of current state**

The code we consider ready to be reviewed (PR #3907) can be found at:

   * https://github.com/shingarov/omr/tree/riscv

"Bleeding edge" RISC-V support can be found at:

   * https://github.com/janvrany/omr/tree/jv/riscv-devel

This branch contains changes we do not yet include in initial PR to keep it smaller or because they're experimental. 

The code is tested (using private CI) both using [QEMU][1] an on real hardware, an [HiFive Unleashed][2] board. Detailed instructions how to compile and test RISC-V support can be found
in [RISC-V compiler build documentation][3] - both native compilation and cross-compilation is supported (and documented).

As of now, 59287 TRIL tests pass (~ 87%)

[1]: https://wiki.qemu.org/Documentation/Platforms/RISCV
[2]: https://www.sifive.com/boards/hifive-unleashed
[3]: https://github.com/janvrany/omr/blob/jv/riscv-devel/doc/compiler/r/Building.md

**Comment by janvrany** [comment]
According to today's discussion, I have separated CMake build support for RISC-V and created a separate PR #4271.

**Comment by janvrany** [comment]
As the initial compiler code has been merged in, shouldn't we close this issue?

**Comment by Leonardo2718** [comment]
We could use this issue to track ongoing work to improve RISC-V support, but I think it's better to just use separate issues. Closing.
