### ISSUE TITLE
Change return type of generated AArch64 instructions

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#4179]
In `compiler/aarch64/codegen/GenerateInstructions.hpp` the return type of each instruction generator is `TR::Instruction *`.  Rather, it should be the precise type of the instruction being generated.  Modify the return type of each generate function in the cpp and hpp file.

**Comment by 0xdaryl** [comment]
@fjeremic @gita-omr @andrewcraik : I see Z and P do the same thing (the return type of the `generateXXXInstruction` is a pointer to the base `TR::Instruction` class rather than the precise class just created).  Is there any reason (historical or otherwise) or advantage for that?  It would seem to give us more flexibility if they returned exactly what they were creating.

**Comment by fjeremic** [comment]
The reason this is done on Z is because of the [Principle of Least Privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege). Every `generateXXXInstruction` starts out returning a `TR:Instruction*` as that is the minimal base class, and in theory should be the only thing the user should care about. If there is a future need to specialize the type to something more concrete, we do so.

However this is almost never necessary, so I question why would need to return the most specific type? Returning the base class gives us most flexibility, so the API can change under the hood without the user caring. For example when a user calls `generateS390CompareAndBranchInstruction` we have full freedom under the hood to generate whatever we want and return the final instruction generated.

In the `generateS390CompareAndBranchInstruction` we may for example check at runtime the CPU we're executing on and determine that we cannot generate a compare and branch instruction because it is not supported, in which case we fall back to generating a separate compare instruction and a branch instruction.

Had we concretely specified the return type we may not have been able to do this because existing code may have started to use APIs on the concrete type.

[1] https://github.com/eclipse/omr/blob/b9ba1f63eafc8b7f4e80c47a0893f16dd8ffdbab/compiler/z/codegen/S390GenerateInstructions.cpp#L289-L362

**Comment by fjeremic** [comment]
I also just did a regex grep for `(static|reinterpret)_cast<TR::S390` in the entire codebase (OMR and OpenJ9) and I cannot find a single instance where we generate an instruction using `generateXXXInstruction` APIs and then cast it to a more concrete type. This further reinforces the lack of need to return very specialized types from these APIs, at least on Z.

**Comment by andrewcraik** [comment]
I think in the case of the x codegen we use the specific instruction types for helpers that are targeted to helping generate specific instructions eg we want to generate a memimm instruction so this is how we do it (call function with opcode and various arguments) and for more semantic things we should use the more abstract type to provide freedom as @fjeremic suggests. I guess the question for the APIs is - are they there as an internal utility to help construct the instruction object/encoding or are they there as semantic helpers. The utilities need the specific type because once you have that instruction you may well care about the parts etc but for the semantic helpers you should not care about how it is implemented.

**Comment by gita-omr** [comment]
I also vote for returning the base class.

**Comment by 0xdaryl** [comment]
OK.  I buy those arguments.  Thanks for the input.  I will close this.
