### ISSUE TITLE
AArch64: Add support for option in register-indexed LDR/STR instructions

### ISSUE THREAD

**Issue by knn-k** [eclipse/omr#4227]
Register-indexed memory access instructions in AArch64 can take options for extending the index register value.
Support for the options in OMRMemoryReference is wanted for performance improvement.

**Comment by knn-k** [comment]
Available options, which are followed by a shift amount.:
- `UXTW`
- `LSL`
- `SXTW`
- `SXTX`

The default is `LSL #0`, i.e. no extension is applied to the index register value.

**Comment by knn-k** [comment]
When it is implemented, it can save one instruction (`sxtw`) in virtual method call in https://github.com/eclipse/openj9/pull/6761 .

**Comment by Akira1Saitoh** [comment]
The shift amount is decided based on the size of LDR/STR instruction. If 32bit load/store, the shift mount is 2. If 64bit, the shift amount is 3. We need to know the size in order to verify that the specified shift amount is correct.
I guess we need to implement that in this issue. https://github.com/eclipse/omr/issues/6087

**Comment by knn-k** [comment]
#6274 implemented this.  Closing.
