### ISSUE TITLE
Committer vote on using clang-format to reformat the OMR repository

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#4631]
# Voting process

The Eclipse Project Handbook [1] outlines the committer voting process for Committer Elections. We will be following the same voting process for this proposal. Just as a reminder, Eclipse summarizes the voting rules as:

1. Committers are required to track, participate in, and vote on, relevant discussions in their associated Projects and components
2. There are 3 voting responses: +1 (yes), -1 (no, or veto), and 0 (abstain)
3. A proposition passes if there are at least 3 positive votes and no negative (veto) votes
4. Vetoes must be followed by an explanation for the veto within 24 hours or it becomes invalid
5. Voting runs for one week, but will end prematurely if all project committers vote +1 or a valid veto vote is casted
6. All votes are conducted via this GitHub issue which will be publicized to all committers

[1] https://www.eclipse.org/projects/handbook/#elections-committer

# What you are voting on

As a committer on the Eclipse OMR project by casting a +1 (yes) vote you are agreeing to all of the following:

1. Eclipse OMR source code will be reformatted using clang-format in a single reformatting commit with a .clang-format [style no. 6](https://github.com/fjeremic/omr/tree/clang-format-3390) proposed in [2] which is a derivation of the style proposed in #3390
    1. Only non-third-party C/C++ code will be reformatted
    2. Amendments to the style can be proposed via the process outlined in 2.
    3. Cleanup in preparation for the reformatting will take place before the reformatting happens, including addition of `// clang-format off` and `// clang-format on` around identified sections of code, etc. to avoid as much unnecessary work post-reformat
2. A formatting amendment process will be defined which will govern how proposed changes to the formatting/tooling will be accepted
    1. Committers will vote on proposed formatting/tooling amendments using the same voting process defined in the previous section (same rules as the Committer Election processes)
    2. Amendments can be proposed before and after the first reformatting commit lands
3. Pull request and merge commit automation will be introduced to check the formatting of each contribution to the project
    1. Pull request checks will be treated by committers the same as a failed test case and will prevent merging of contributions until the check passes
4. The project will provide a migration story for in-flight work which is based on a commit prior to the reformatting
    1. An automated Bash script will be provided which will rebase a branch from a pre-format commit to a post-format commit
    2. An algorithm will also be provided consisting of `git` commands which can be followed to rebase a branch from a pre-format commit to a post-format commit (a pseudo-code explanation of 4.1.)
5. The reformatting will take place in late December 2019, or early January 2020
    1. All automation, documentation, and notice of the migration story for in-flight work will take place prior to the actual commit being contributed to the master branch

[2] https://github.com/eclipse/omr/issues/4577#issuecomment-557829496

# Details

### Cleanup preparation (1.1 & 1.3)

Some code areas identified, such as the one stated in [3] and [4], will be addressed prior to the reformatting. In addition `.clang-format` files will be added in all third-party directories with a `DisableFormat: true` clause to prevent clang-format from applying the global style to third-party code.

In addition any areas identified, such as tabular data, ASCII art, complex macro definitions will be guarded with `// clang-format off` and `// clang-format on` prior to the reformatting. We will undoubtedly find additional areas which need fixing as we read and modify code. Such areas will be fixed by contributors in future PRs.

The SHA of the first reformatting commit as well as any future amendments will be added to a `.git-blame-ignore-revs` list for `git blame` / `git hyper-blame` to properly ignore formatting during history searches.

[3] https://github.com/eclipse/omr/issues/4577#issuecomment-558165548
[4] https://github.com/eclipse/omr/issues/4577#issuecomment-558669316

### Amendment process (2.1 & 2.2)

The style is not set in stone and will naturally evolve with the project. The voting process being the same for the initial style as well as amendments (hopefully) ensures a reasonable path forward.

While we will require a committer vote on future amendments to the formatting style we should try to get most of these out of the way before the first reformatting actually lands. This will reduce the churn on the codebase and we will have less commits to ignore on the `.git-blame-ignore-revs` list.

### Automation (3 & 4.1)

Sample automation has been implemented on a personal fork as an example of what can be done. The automation runs an extra job as part of the Travis CI build which `clang-format` checks that each commit within a PR is in conformance with the project defined style. The automation then uses the GitHub Status API to tag the HEAD commit in the PR with a separate status badge indicating pending/success/failure of the clang-format job.

You can find the sample automation here (note the two PR checks that happen as part of a single Travis build):
https://github.com/fjeremic/omr-clang-format-automation/pulls

The automation implements [MongoDB's algorithm](https://engineering.mongodb.com/post/succeeding-with-clangformat-part-3-persisting-the-change) for rebasing PRs which were opened before the formatting took place onto commits representing the same changes after the formatting. This is all done via automation so hopefully not much action for the end-user other than running the script. There are two PR examples on the fork which demonstrates reformatting of existing OMR PRs (#4555 and #4598) pre-format to post-format conformance in an automated way.

In case the automation identifies a formatting error it will provide a git patch file which the user can copy and apply to their commit to fix up the formatting without even having `clang-format` installed.

You can see and example of this in the following PR:
https://github.com/fjeremic/omr-clang-format-automation/pull/3

by following the "Details" link on the failed continuous-integration/travis-ci/clang-format job and looking at the build output for patch file which is displayed. Applying the patch file correctly formats the commit in a way that the formatting check will pass.

# Vote summary

Voting deadline:
December 10th, 2019 5:00 p.m. EST (UTC -05:00)

https://projects.eclipse.org/projects/technology.omr/who

| Committer                          | Response | 
|------------------------------------|----------| 
| Andrew Craik (@andrewcraik)        |          | 
| Andrew Young (@youngar)            |          | 
| Charlie Gracie (@charliegracie)    |          | 
| Daryl Maier (@0xdaryl)             | [+1 (yes)](https://github.com/eclipse/omr/issues/4631#issuecomment-561667150) | 
| Filip Jeremic (@fjeremic)          | [+1 (yes)](https://github.com/eclipse/omr/issues/4631#issuecomment-561375285) | 
| John Duimovich (@jduimovich)       |          | 
| Leonardo Banderali (@Leonardo2718) | [+1 (yes)](https://github.com/eclipse/omr/issues/4631#issuecomment-561405729)  | 
| Mark Stoodley (@mstoodle)          | [-1 (no)](https://github.com/eclipse/omr/issues/4631#issuecomment-563307926) | 
| Robert Young (@rwy0717)            |          | 
| Vijay Sundaresan (@vijaysun-omr)   | [+1 (yes)](https://github.com/eclipse/omr/issues/4631#issuecomment-561662475)  |

**Comment by fjeremic** [comment]
+1 (yes)

**Comment by Leonardo2718** [comment]
+1 (yes)

**Comment by vijaysun-omr** [comment]
+1 (yes)

**Comment by 0xdaryl** [comment]
+1 (yes)

**Comment by charliegracie** [comment]
A quick question before I vote as I have missed some of the meetings. The format that was settled on was a derivation of WebKit style correct?

**Comment by fjeremic** [comment]
> A quick question before I vote as I have missed some of the meetings. The format that was settled on was a derivation of WebKit style correct?

That's correct. You can see the entire repository in the proposed style here:
https://github.com/fjeremic/omr/tree/clang-format-3390

**Comment by mstoodle** [comment]
I have voted -1 to this proposal and I want to explain my reasoning. I did not make this decision lightly and I still feel very conflicted over it, but I cannot in good conscience vote to support this proposal because ultimately I believe that it will do more harm to the project than good.

This proposal, I believe, originally came from a desire to bring together two disparate code bases that have been brought into the same Git repository, as well as the teams of developers that *mostly* work in one or the other. The JIT component was created by a different team of developers than the team that created the rest of the OMR project (and the same division exists in Eclipse OpenJ9 as well). Those teams naturally and independently developed different code formats that, after 15+ years evolving on their own, were brought together in one repository in 2016 or so. There is a natural sense of familiarity and pride in those two code bases. But anyone who has to work across these two code bases faces a big challenge because the code formats are *very* different. To some, myself included, this difference is seen as a natural forcing function that acts to keep divided the two groups of developers who specialize in each part of the OMR project. In effect: our code reinforces two separate teams of developers and introducing a single code format was meant as a relatively "cosmetic" step to start sealing this division. I truly wish we could mend this very visible display of division, but I am not convinced that this proposal can do that.

There are a lot of developers in our community with very strong opinions on their current code format. They have strong opinions on the value of the code itself and have grave concerns over the impact to senior developer productivity and the serviceability of the code. I can not and will not discount these opinions because I share them, at least in part. There is no denying that the code would change, that some parts of the code base would change for the worse, and that activities like comparing code to older releases would become more difficult. These are effects whose impact would lessen over time and there are tooling solutions that could help lessen the pain for some of them, but I still think a lot of people will be impacted immediately after this change is made.

In the end, as an OMR project lead, I have to endeavour to represent the interests of everyone who brings their time and effort to building and enhancing this project. That doesn’t just include the committers, all of whom I have the utmost respect for, but also the huge group of contributors who work in this project on, in many cases, a daily basis. I believe a large enough number of those contributors will be unhappy following this change and that their unhappiness will impact the reputation and "mood" of this project. Though I would like to believe we’re all professional enough to adapt to change, that doesn't necessarily translate into license to proceed with a proposal that seems to me like it would drive the wedge (that we’re actually trying to eliminate) deeper into our community.

For these reasons, I have voted to veto *this* proposal. I know this decision will also disappoint many contributors to our project. But I am still hopeful there is some kind of progress we can make on this front. I think unless everyone in the community is willing to make some concessions (which I haven’t seen yet), however, our options become quite limited to solve this code division problem and hence the community division problem.

But I am continually inspired by the creativity and ingenuity of this community, so maybe we can find a way forward that I haven’t thought of yet. I look forward to your suggestions and continued willingness to discuss this challenge.

As a final note, I would like to thank those members of our community who have invested so much time and effort to research, produce, gather and account for feedback, and iterate to create this proposal. I know it was a lot of work, a lot of personal investment, and I am truly torn by having to vote no to it. Please do not take my veto as personal or disrespecting your opinions. I highly respect the work you’ve done and, as I said above, hope that there is still some path forwards that can achieve the very valuable goals you set out to tackle. Thank you for your contribution to making this community stronger and better.

**Comment by fjeremic** [comment]
The one week deadline has now passed and the voting is complete. There have been no objections to the reason behind the veto vote, so the veto is valid and is accepted. The OMR project will _not_ be implementing the proposed change defined within this issue.

Thank you everyone for investing the time to read and vote on the proposition, and I too hope we can still find a path forward to achieve this goal at some point in the future.
