### ISSUE TITLE
Z evaluator problems for fselect, dselect 

### ISSUE THREAD

**Issue by mstoodle** [eclipse/omr#4953]
#4952 introduced new cross platform tests for the `fselect` and `dselect` compiler opcodes that surfaced a couple of problem, as described in this comment: https://github.com/eclipse/omr/pull/4952#issuecomment-601229796 .

The tests have been temporarily disabled for the Z platform. Once these problems addressed, those tests should be re-enabled.

**Comment by fjeremic** [comment]
Looking at the tree evaluator table for `fselect` there is a clear error here in that it is using the GPR evaluator, instead of the FPR one. That's the first problem. The second one is that the `dselect` evaluator seems to just blatantly assume we have vector support without even checking [2].

We need to validate that `dselect` is even correct as it stands, and implement a proper fallback path for our minimum supported ALS (z9).

@r30shah could you help investigate and fix this one? Please re-enable the disabled tests as part of the fix.

[1] https://github.com/eclipse/omr/blob/1679756b7b1b5674cf22a856d78018079e2d2f07/compiler/z/codegen/OMRTreeEvaluatorTable.hpp#L445-L446
[2] https://github.com/eclipse/omr/blob/1679756b7b1b5674cf22a856d78018079e2d2f07/compiler/z/codegen/ControlFlowEvaluator.cpp#L2722-L2822

**Comment by r30shah** [comment]
@fjeremic  Sure, let me take a look
