### ISSUE TITLE
Capitalize TLS macros

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#6050]
As outlined in https://github.com/eclipse/omr/pull/6030#discussion_r646891358 review comment the `tlsFree` and it's sibling macros look like function calls. We should capitalize these macros to abide by the unwritten convention that macros are capitalized, so people don't assume they are function calls.

**Comment by fjeremic** [comment]
@dsouzai FYI.

**Comment by 0xdaryl** [comment]
@dylanjtuttle : please have a look at this

**Comment by dylanjtuttle** [comment]
@0xdaryl I've noticed that macros named `TLS_ALLOC`, `TLS_SET` and `TLS_GET` are also defined in [include_core/unix/thrdsup.h](https://github.com/dylanjtuttle/omr/blob/31dbcfef0bec1b68a807b7fe49e8cb3c7ced9304/include_core/unix/thrdsup.h#L318) and [include_core/win/thrdsup.h](https://github.com/dylanjtuttle/omr/blob/31dbcfef0bec1b68a807b7fe49e8cb3c7ced9304/include_core/win/thrdsup.h#L138), and appear to do different things than the macros that I am renaming as far as I can tell. I noticed this when, after renaming, my local build failed with errors stating that the above three macros were being redefined.

I'm hesitant to name these macros something different just to avoid the errors, since I feel that would be confusing. How do you think I should rename them?

**Comment by dsouzai** [comment]
One option is you could name it `TR_TLS_...` since these are compiled defined TLS macros.
