### ISSUE TITLE
DDR DwarfParser for AIX

### ISSUE THREAD

**Issue by VermaSh** [eclipse/omr#606]
Need to modify DwarfParser to accept AIX symbol table as input.

**Comment by VermaSh** [comment]
Here are some notes that might be helpful using the AixSymbolTableParser
[Notes.txt](https://github.com/eclipse/omr/files/655932/Notes.txt)

**Comment by VermaSh** [comment]
Here's a link to the documentation for AIX symbol table http://www.ibm.com/support/knowledgecenter/ssw_aix_71/com.ibm.aix.files/XCOFF.htm

**Comment by VermaSh** [comment]
This zip file has a tester file and sample output.
[for_reference.zip](https://github.com/eclipse/omr/files/658082/for_reference.zip)

TIPS: When reading the file record, check the size of that file to see if it needs to be used or not.
size = 0 will be for system include files

TODO: Maybe change the getNextFile to return a pointer to the file structure instead of writing out just the insertion key

**Comment by VermaSh** [comment]
# **BUG!!!**

The condition that checks for insertion key overlap should be
 if (existing_entry->second.declFile != declData->declFile) 
instead of == as the symbol table first declares each class and then has another entry with all the fields of the class
so for example
for class A
A:T6=Y0s(;
`A:T6=Y8s(u:x:9,0,32;u:y:8,32,16;;`
There will be two entries in the symbol table. So with the current condition, when the parser reaches to the second line it will take that as an error but it isn't an error because we are just updating the record for class A.

The only time it could be an error is if the declFile are not the same. That would mean that the records from two different files have the same insertion key. 

look for:  "ERROR>>>>There was a overlap in insertion keys" line: 1608
This is why the output log, Final.txt file in the for_reference.zip, has overlap in insertion key error messages

**Comment by twlogger** [comment]
File IDs were being set in an incorrect way previously (They used the index given in the symbol table, which wasn't guaranteed to be unique). 

This wasn't discovered in testing with the test compiled files found in omr/tools/ddrgen/test, as they only created one object file (within object files, the indices in the symbol table are guaranteed to be unique). 

When testing with an archive file (libomrstatic.a), I discovered that the symbol table indices return to zero for each .o file in the archive. 

This problem has been resolved, I'm now using the filenames as strings to index the DIEs in the unordered_map. 

In order to futureproof/ensure that this strategy will ensure unique filenames/no overlap (different directories might have .cpp files with the same name, header files might be included more than once), even when the parser is run on multiple files (possibly in different directories), we need to get the full file paths for each file being compiled.

**Comment by twlogger** [comment]
**No Symbol** is not guaranteed to indicate the end of the declaration section in the symbol table. This was discovered in testing libomrstatic.a. 

This problem is resolved (for now), since declarations occur in a contiguous sequence, I simply break after a line which isn't a declaration appears.

**Comment by twlogger** [comment]
The symbol tables may contain negative type numbers outside of the range given here: https://sourceware.org/gdb/onlinedocs/stabs/Negative-Type-Numbers.html#Negative-Type-Numbers (for example, -35, -36) - I will need to change the value of sizetype (which is currently -35) to some value that is guaranteed to not be defined by the AIX symbol table as something else. 

-35 seems to be for intptr_t, and -36 for uintptr_t. 

IBM documentation provides no details either. 

I will investigate this further.

**Comment by twlogger** [comment]
The current scheme for detecting files that have already been scanned simply skips over those scanned files when they are found in symbol tables after the first one. 

Thus, if two symbol tables contain only one file, then when the second time the file is found while parsing the second symbol table, the compilation unit and dwarf die for the compilation context are not created, and in getBlacklist, getting the compilation unit die fails (the die is null).

DwarfScanner.cpp possibly needs to be modified to account for this case, or in the case when nothing is found, AixDwarfParser.cpp could create a CU and a CU die with empty/zero values, for the sake of compatibility with the DwarfScanner without having to modify it.

For now, I will implement this second solution.

**Comment by charliegracie** [comment]
The work for this has been completed.  Closing
