### ISSUE TITLE
Ruby JIT multiplexing pseudo-TOC on sys TOC

### ISSUE THREAD

**Issue by zl-wang** [eclipse/omr#665]
After pull request #612 was merged, Ruby tests started to fail. 
Finding out unfortunately Ruby JIT is multiplexing JIT pseudo-TOC on sys TOC register.

**Comment by mgaudet** [comment]
Is there a more permanent fix we should be making about the TOC? _ie_ Mandating a certain usage pattern for it?

**Comment by zl-wang** [comment]
TOC usage pattern is fixed and specified by the ABI:  caller needs to set up for the callee across a module. And, caller needs to restore its own upon return.

JIT pseudo-TOC, on the other hand, is another single table used by all JIT-ed code.  From original design, it was based off another (preserved) register.

Discovering whether it is multiplexed as in Ruby JIT took the roundabout.  Not sure about 32bit Ruby (is there?) status, but keeping the original code is a safe bet.

**Comment by mgaudet** [comment]
No such thing as 32 bit Ruby. :) So that's one good thing. 

When you say 'Multiplexed' here, and in the commit message, I am not quite sure what you mean; Is it just that the preserved register (`r2`) is being shared between JIT and non-JIT code for TOC usage -- [Hence the need to generate a TOC restore](https://github.com/zl-wang/omr/commit/dd1b0efc9428279c42acce8cc3e99b61f0242204#diff-8667a28b4e5624311cf3283984358c37R1472)?

**Comment by zl-wang** [comment]
There is system TOC and there is JIT pseudo TOC.  In Ruby, it appeared that r2 is used to hold the base address of JIT pseudo-TOC when the control flow is in JIT-ed code.  r2 needs to hold the base address of system TOC when the control flow is in ABI-conforming code (by definition).  This deviates from Java JIT where r2 is not multiplexed as such (r16 is dedicated for JIT pseudo-TOC).

**Comment by ymanton** [comment]
I think the system linkage code in OMR still needs some work (probably on all platforms). This code cannot stand on it's own as-is; without knowing about the ABI conventions of the **caller** it can't really do it's job, it knows about the ABI conventions of the **callee** but you really need some coordination between the two.

In the past this worked fine because the system linkage code was written to assume that the caller was following the Java JIT private linkage conventions, and the code would then generate code that was appropriate for transitioning from Java JIT to system and back. This implicit assumption cannot be made in OMR; in order to generate calls to a callee that follows a particular ABI you need to know some things about the caller's ABI as well.

**Comment by 0xdaryl** [comment]
Well said, @ymanton.  In general, the system linkage as implemented in OMR is a subset of what the full API says is possible (e.g., vararg support is missing in some (all?) OMR platform implementations).  I have been meaning to create an issue to track making system linkage fully compliant on all architectures so that it behaves as a consumer would expect.

**Comment by kaiwalyajoshi** [comment]
Something must have horribly broken, lots of messages here.
We implemented enough of System Linkage back then to get Rails running, not sure what the situation is now. The intention back then was to only have System Linkage, no Private Linkage, hence r16 cannot be used. Ruby flies back and forth between the interpreter and JIT far more rapidly than does Java, infact more code ran in interpreter than JIT (few methods could be JITed) hence r2 stays the same most of the time, and when we do enter into JIT we swap it out for the pTOC.

**Comment by ymanton** [comment]
Nothing was broken recently, we just resurrected 32-bit Power Linux support for the Java JIT and this code, after it was refactored for OMR, finally started being exercised on that platform.

On 32-bit Power Linux `r2` is not the system TOC register, it's the OS's thread control block pointer and should not be touched by anyone. Putting the JIT pTOC in `r2` is going to cause bad things to happen when the kernel goes to context switch the thread and tries to access the TCB in `r2`.

There is no TOC on 32-bit Power Linux, there's a GOT, which is similar, but it doesn't have a fixed register that you can multiplex with the JIT pTOC.

**Comment by 0xdaryl** [comment]
Fixed.  Closing this.  System linkage does need to be "rounded out" to be complete on all architectures but that is not the subject of this issue.
