### ISSUE TITLE
The Philosophy of the TR:: Namespace 

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#788]
There've been some discussions about the purpose and philosophy of the `TR::` namespace in the compiler component. I'm opening this issue to mention that we're working on trying to nail down the defintions in documentation. The driving question has been "Does it make sense to have namespaces underneath `TR`"? 

We had some in person discussion, and I came down with the following description and philosophy of the `TR::` namespace: 

> The `TR::` namespace is for talking about complete ideas. 

The compiler component adopts [extensible classes](https://github.com/eclipse/omr/blob/master/doc/compiler/extensible_classes/Extensible_Classes.md) to provide extension, which means that there are some classes that exist in the class hierarchy that are in a sense 'incomplete' _ie_, an `OMR::Instruction` isn't completed until its been subclassed by at least an architecture. Once the class is completed, that is the point at which we map it into the `TR::` namespace. This is an indicator to consumers (both people and tools) that the extension is now complete, and so the type can be talked about outside the context of completing it. 

It's worth calling out explicitly: This totally supports and encourages the creation of classes that are already completed directly in the `TR` layer. 

As a result of this, it doesn't make sense to create namespaces below `TR`

If we're OK with this definition, I plan on drafting some documentation to check in to the source code to make this explicit.

**Comment by mstoodle** [comment]
"complete" may be the best way to describe it, but it's kind of a project-centric notion of complete i.e. what's complete for one project may not be complete for another project because not all classes need to be extended by all projects. Through the course of developing a compiler project, classes that start out being "complete" in OMR may end up being more "complete" through extension. So I find that a bit weird, but without a better metaphor to suggest right now, I think I can accept complete.

**Comment by mgaudet** [comment]
I definitely agree "Complete" Is kind of funny. In previous conversations (and [in the `OMRChecker`](https://github.com/eclipse/omr/blob/master/tools/compiler/OMRChecker/OMRChecker.hpp#L61)) I've used the term "Concrete" class. However, "Concrete" only makes sense in the context of extensible classes vs. "Complete" encompasses classes we just put into the `TR::` namespace directly. 

I'm open to other terms ¯\_(ツ)_/¯

**Comment by Leonardo2718** [comment]
Perhaps a single word is not quite descriptive enough.

"Complete" by itself can have different interpretations. Even C++ has a definition for what a "Complete type" is (or rather, what an "Incomplete" type is). Maybe we should be more explicit about what is meant by "Complete" in our definition.

With that said, I'm not sure I follow the reasoning for why "it doesn't make sense to create namespaces below `TR`". Could this be elaborated on? As an example of my thinking, I don't see how a `TR::Experimental` or a `TR::Deprecated` namespace would violate the above definition.

**Comment by mstoodle** [comment]
The main point of the TR namespace is so that every *other* class knows where to go to find every other class without knowing how it is assembled. I suppose "fully assembled" could be another word for "complete".  i.e. every class other than the building blocks for Instruction refer to it as TR::Instruction. Only the Instruction classes themselves, from their various projects and architectures, know how TR::Instruction should be formed. It avoids the need for a template parameter (exposed to everything in the hierarchy) to tell each class the name of the most refined class, as in CRTP, which means we can create extensible classes without needing templates. Having written a few extensible class hierarchies when we were evaluating CRTP and similar approaches, I distinctly prefer to avoid templates for this particular use case.

If there's a namespace like Experimental under TR, then every other class needs to know it's in the Experimental namespace, and promoting it from Experimental means changing every class that refers to it to remove that namespace (or you do something very less satisfying like rely on "using" to find it).  

Maybe TR == Totally Reified :)

**Comment by Leonardo2718** [comment]
@mstoodle I see you're point about extensible class hierarchies.

However, this to me implies a much more specific definition than the above (if I understood correctly) because "fully assembled" is specifically defined for extensible classes. So, I guess my next question is: what does it mean for a _non-extensible_ class (hierarchy) to be "Complete" or "Fully Assembled"?

**Comment by mstoodle** [comment]
I suppose a non-extensible class would be fully assembled by, ahem, "definition" ? :)

I was only half kidding on TR=Totally Reified...only problem is that it's hard to say it in your head without a valley girl accent once you've imagined it once :) . Maybe there's a better "T" word than Totally, but Reified is pretty accurate IMO. Testarossa Reified ?

**Comment by mstoodle** [comment]
For the record and for those not already in the know, TR originally stood for Testarossa, the "code name" of the compiler project at IBM from which this technology originates.

**Comment by Leonardo2718** [comment]
Okay, I didn't quite ask the right question. What I really meanted to ask is: what does it mean for _anything other_ than an extensible class (non-extensible class, namespace, function, etc.) to be "fully assembled" or "complete"? Is there a reason for a namespace to be considered "incomplete" other than just "by definition"?

I'm really just trying to define the `TR` namespace in terms of what should go in it vs what shouldn't. Ideally, the definition should have some conceptual foundation to it.

**Comment by mstoodle** [comment]
Anything that should be referenced directly by other classes?  Any class that is usable on its own is, of course, fully (totally) reified. I think *classes* can be complete, but the adjective should not be applied to namespaces. Namespaces other than TR are used to organize functionality for assembling complete classes. 

That definition may motivate quite a few classes to move from OMR to TR, though, which makes @Leonardo2718's question extremely important. I have already been less than enthused about some classes being in OMR and some being in TR (e.g. OMR::VirtualMachineState from the JitBuilder world is in the OMR namespace but TR::IlBuilder is from TR namespace.....from consumability standpoint it falls way less than stellar). Consumers shouldn't have to be aware of how a class is put together (whether as a standalone class or through project/architecture extensions).

**Comment by Leonardo2718** [comment]
I can accept @mstoodle's definition (thanks btw!).

> I think classes can be complete, but the adjective should not be applied to namespaces. Namespaces other than TR are used to organize functionality for assembling complete classes.

If this is the convention we agree on, it **needs to be clearly documented** somewhere.

**Comment by mgaudet** [comment]
So what about this as a candidate for merging into the extensible class documentation: 

> In the compiler technology, extensible classes are created across a number of different namespaces. In order to provide a concrete name that's usable anywhere, we map all our extensible classes into the `TR::` namespace at the end. The `TR::` namespace is used in the compiler technology for referencing complete concepts. This means that it is perfectly legitimate to create a class directly in the `TR::` namespace if it's complete and can and should be used as is.

**Comment by mstoodle** [comment]
Maybe a "to provide a single concrete name that can be used anywhere" ?

"at the end" -> "when fully created" ?

"is used in" -> "should be used throughout"

"This means that" -> "" (unqualified use of "this" is a pet peeve of mine)

Putting classes directly into the TR namespace has an additional benefit in that, in combination with careful use of "virtual", it gives the OMR project some control over what concepts should be considered extensible. Things that the code base expects to be extensible are readily identifiable. The flip side is that missing but safe flexibility isn't "just there". In the absence of ugly counter examples, I think I'm ok with that trade-off.

**Comment by mstoodle** [comment]
Maybe move the review into a PR at this point?

**Comment by mgaudet** [comment]
Done: #817

**Comment by mgaudet** [comment]
Closed in #817
